import {
  americanFootballOutline,
  basketballOutline,
  baseballOutline,
  barbellOutline,
  bonfireOutline,
  footballOutline,
  footstepsOutline,
  fitnessOutline,
  heartOutline,
  bicycleOutline,
  golfOutline,
  airplaneOutline,
  pulseOutline,
  balloonOutline,
  boatOutline,
  gameControllerOutline,
  busOutline,
  codeSlashOutline,
  fishOutline,
  mailOutline,
  pizzaOutline,
  schoolOutline,
  terminalOutline,
  trainOutline,
  trophyOutline,
  restaurantOutline,
  bookOutline,
  brushOutline,
  colorFillOutline,
  colorPaletteOutline,
  constructOutline,
  easelOutline,
  imageOutline,
  musicalNoteOutline,
  musicalNotesOutline,
} from "ionicons/icons";

export const sportIcons = {
  pulseOutline,
  fitnessOutline,
  americanFootballOutline,
  basketballOutline,
  baseballOutline,
  barbellOutline,
  bonfireOutline,
  footballOutline,
  footstepsOutline,
  heartOutline,
  bicycleOutline,
  golfOutline,
};

export const activityIcons = {
  airplaneOutline,
  balloonOutline,
  boatOutline,
  gameControllerOutline,
  busOutline,
  codeSlashOutline,
  fishOutline,
  mailOutline,
  pizzaOutline,
  schoolOutline,
  terminalOutline,
  trainOutline,
  trophyOutline,
  restaurantOutline,
};

export const artIcons = {
  bookOutline,
  brushOutline,
  colorFillOutline,
  colorPaletteOutline,
  constructOutline,
  easelOutline,
  imageOutline,
  musicalNoteOutline,
  musicalNotesOutline,
};

export const DARK_MODE_KEY = 'DARK_MODE';
export const IS_AUTO_THEME = "IS_AUTO_THEME"